# Wayland Environment Variables
# See: https://wiki.archlinux.org/title/Environment_variables#Per_user

# Electron apps
ELECTRON_OZONE_PLATFORM_HINT=auto
NIXOS_OZONE_WL=1

# GTK
GDK_SCALE=1
GDK_DPI_SCALE=1

# Qt
QT_SCALE_FACTOR=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=gtk2

# SDL
SDL_VIDEODRIVER=wayland

# Java
_JAVA_AWT_WM_NONREPARENTING=1
